server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/money_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user_tuto
    password: 1234
  thymeleaf:
    cache: false

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hidernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false


